export {default as Home} from './home.jsx'
export {default as LoginPage} from './login.jsx'
export {default as SignUpPage} from './signup.jsx'
export {default as NotFoundPage} from './404.jsx'
export {default as StudentDashboard} from './studentView.jsx'