//I recommend using rest client extension within vscode

//Register
POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "admin",
    "password": "admin",
    "role": "admin"

}


###

//Login
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

//Username
GET http://localhost:5000/profile
Content-Type: application/json

###
//logout
POST http://localhost:5000/users/logout

###

//conversation
POST http://localhost:5000/conversation
Content-Type: application/json

{
    "id": 1,
    "user": "admin",
    "text": "help!!"
}